const UPDATING_USER = "user:UPDATING_USER";
const DELETE_USER = "user:DELETE_USER";
const GET_USER = "user:GET_USER";
const FOLLOWING_USER = "user:FOLLOWING_USER";
const UNFOLLOWING_USER = "user:UNFOLLOWING_USER";
module.exports = {
  UPDATING_USER,
  DELETE_USER,
  GET_USER,
  FOLLOWING_USER,
  UNFOLLOWING_USER,
};
